stages:
  - test
  - build

lint-job:
  stage: test
  tags:
   - docker
  image:
   name: docker/golangci-lint:1.64.8-go1.24.3
  script:
    - mkdir -p /app/src
    - cp -r $CI_PROJECT_DIR /app/src
    - ls -la /app/src
    - echo "Linting code..."
    - golangci-lint run -c /app/src/IvolgaOledManager/.golangci.yml /app/src/IvolgaOledManager/...

build-job:
  stage: build
  tags:
   - docker
  image:
   name: golang:1.24.4-alpine3.22 # docker/golangci-lint:1.64.8-go1.24.3
  script:
    - mkdir -p /app/src
    - cp -r $CI_PROJECT_DIR /app/src
    - echo "Compile project..."
    - GOOS=linux GOARCH=arm GOARM=7 go build -o /app/src/IvolgaOledManager/bin/ssc_hms_display /app/src/IvolgaOledManager/cmd/display/main.go
