stages:
  - test
  - build

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

default:
  image: golang:1.24.4-alpine3.22
  tags:
    - docker
  before_script:
    - cd $CI_PROJECT_DIR

lint-job:
  stage: test
  script:
    - echo "Install linter..."
    - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.2.1
    - golangci-lint --version
    - echo "Lint code..."
    - golangci-lint run -c ./.golangci.yml ./...

build-job:
  stage: build
  script:
    - echo "Compile project..."
    - GOOS=linux GOARCH=arm GOARM=7 go build -o ./bin/ivolga_oled_manager ./cmd/display/main.go
    - ls -la ./bin/
  artifacts:
    paths:
      - ./bin/ivolga_oled_manager
