stages:
  - test
  - build

variables:
  DOCKER_DNS: "1.1.1.1" # for DNS resolving

before_script:
  - cat /etc/resolv.conf  # Проверить, какие DNS использует контейнер
  - ping -c 4 8.8.8.8

lint-job:
  stage: test
  tags:
   - docker
  image:
   name: alpine:3.22
  script:
    - echo "Clone repo..."
    - git --version
    - cp -r $CI_PROJECT_DIR /
    - ls -lA /
    - echo "Install linter..."
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s v2.2.1
    - golangci-lint --version
    - echo "Lint code..."
    - golangci-lint run -c /IvolgaOledManager/.golangci.yml /IvolgaOledManager/...

build-job:
  stage: build
  tags:
   - docker
  image:
   name: golang:1.24.4-alpine3.22
  script:
    - cp -r $CI_PROJECT_DIR /
    - echo "Compile project..."
    - GOOS=linux GOARCH=arm GOARM=7 go build -o /IvolgaOledManager/bin/ivolga_oled_manager /IvolgaOledManager/cmd/display/main.go
