stages:
  - test
  - build

lint-job:
  stage: test
  tags:
   - docker
  image:
   name: golang:1.24.4-alpine3.22
  script:
    - echo "Clone repo..."
    - cp -r $CI_PROJECT_DIR /
    - ls -lA /
    - echo "Install linter..."
    # - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s v2.2.1
    # - ./bin/golangci-lint --version
    - for (( num=0; num < 5; num++ )); do
        echo "Attempt $i..."
        wget https://github.com/golangci/golangci-lint/releases/download/v2.2.1/golangci-lint-2.2.1-linux-amd64.tar.gz && break || sleep 5;
      done
    - tar -xzf golangci-lint-2.2.1-linux-amd64.tar.gz
    - cp golangci-lint-2.2.1-linux-amd64/golangci-lint /usr/local/bin/
    - golangci-lint --version
    - echo "Lint code..."
    - cd /IvolgaOledManager
    - golangci-lint run -c ./.golangci.yml ./...

build-job:
  stage: build
  tags:
   - docker
  image:
   name: golang:1.24.4-alpine3.22
  script:
    - cp -r $CI_PROJECT_DIR /
    - echo "Compile project..."
    - cd /IvolgaOledManager
    - GOOS=linux GOARCH=arm GOARM=7 go build -o ./bin/ivolga_oled_manager ./cmd/display/main.go
