stages:
  - test
  - build

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

default:
  image: golang:1.24.4-alpine3.22
  tags:
    - docker
  before_script:
    - cd $CI_PROJECT_DIR

lint-job:
  stage: test
  script:
    - echo "Install linter..."
    - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.2.1
    - golangci-lint --version
    - echo "Lint code..."
    - golangci-lint run -c ./.golangci.yml ./...

unit-tests-job:
  stage: test
  script:
    - go test -v -cover ./internal/pkg/... ./internal/app/entity/...

db-tests-job:
  stage: test
  services:
    - name: mysql:9.3.0
      alias: mysql-test
      variables:
        MYSQL_ROOT_PASSWORD: "password"
        MYSQL_DATABASE: "test_db"
  variables:
    TEST_DB_DSN: "root:password@tcp(mysql-test:3306)/test_db?parseTime=true&timeout=10s"
  before_script:
    - echo "Waiting for MySQL..."
    - apk add --no-cache wait4x
    - wait4x -t 60s mysql "$TEST_DB_DSN"
  script:
    - apk add --no-cache mysql-client
    - TEST_DB_DSN="$TEST_DB_DSN" go test -v -cover ./internal/app/repo/...

build-job:
  stage: build
  script:
    - echo "Compile project..."
    - GOOS=linux GOARCH=arm GOARM=7 go build -o ./bin/ivolga_oled_manager ./cmd/display/main.go
    - ls -lAh ./bin/
    - echo "Compress binary..."
    - gzip -9 ./bin/ivolga_oled_manager
    - ls -lAh ./bin/
  # artifacts:
  #   paths:
  #     - ./bin/ivolga_oled_manager.gz
